config/routes.rb
Rails.application.routes.draw do

	resources :blogs

	devise_for :users, path: '', path_names: {
			sign_in: 'login',   # 'users/sign_in' => 'login'
			sign_out: 'logout', # 'users/sign_out' => 'logout'
			sign_up: 'register' # 'users/sign_up' => 'register'
	}, controllers: {
			omniauth_callbacks: 'users/omniauth_callbacks'
	}

	root to: "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################


  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: [:google, :github]

  # devise automatically requires email & password
  validates_presence_of :name

  # delete the user, delete the blog
  has_many :blogs, dependent: :destroy

  # set default user role
  after_create :set_role

  def set_role
    self.roles = 'editor'
    self.save
  end

  # generate user based on omniauth data received from 3rd party providers
  def self.from_omniauth(auth)
    user = User.find_by_email(auth.info.email.downcase)
    # user has an existing account via devise/google
    if user
      self.update_user_attributes(user, auth)
    else
      self.sign_in_with_provider(auth)
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = (session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]) ||
          (session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"])
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # generate first & last name
  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end


  private
    def self.update_user_attributes(user, auth)
      user.update_attributes(provider: auth.provider, uid: auth.uid)
      user
    end

    def self.sign_in_with_provider(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.skip_confirmation! # don't send the user a confirmation email
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # call application concerns
  include DeviseWhitelist
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # guest user can view and list blogs, logged in users can create, update and destroy blogs, admins can do everything
  access [:all, :user] => [:index, :show], [:editor, :admin] => [:index, :show, :new, :create, :edit, :update, :destroy]

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    if @blog.user.id == current_user.id || logged_in?(:admin)
      render :edit
    else
      redirect_to @blog, notice: 'Permission Denied'
    end
  end

  # POST /blogs
  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.user.id == current_user.id || logged_in?(:admin)
      if @blog.update(blog_params)
        redirect_to @blog, notice: 'Blog was successfully updated.'
      else
        render :edit
      end
    else
      redirect_to @blog, notice: 'Permission Denied'
    end
  end

  # DELETE /blogs/1
  def destroy
    if @blog.user.id == current_user.id || logged_in?(:admin)
      @blog.destroy
      redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
    else
      redirect_to blogs_path, notice: 'Permission Denied'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :content, :user_id)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern

	#  override the devise current_user method
	def current_user
		# if no user is logged in return the guest user
		super || guest_user

	end

	private
		def guest_user
			# OpenStruct.new(
			# 			name: 'Guest User',
			# 			first_name: 'Guest',
			# 			last_name: 'User',
			# 			email: 'guest@example.com'
			# 	)

			# because petergate gem access the user model, refactor guest_user
			# to inherit from User model
			guest = GuestUser.new
			guest.name = "Guest User"
			guest.first_name = "Guest"
			guest.last_name = "User"
			guest.email = "guest@example.com"
			guest
		end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do
		# devise whitelist - define what user parameters are accepted
		before_action :permitted_devise_parameters, if: :devise_controller?
	end

	def permitted_devise_parameters
		# additional parameters, email and password are accepted by default
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name]) # edit
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index

	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	# google callback
	def google
		callback_from(:google)
	end

	# github callback
	def github
		callback_from(:github)
	end

	def failure
		flash[:error] = "There was a problem signing in"
		redirect_to root_path
	end


	private
		def callback_from(provider)
			@user = User.from_omniauth(request.env['omniauth.auth'])
			if @user.persisted?
				sign_in_and_redirect @user
				set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
			else
				session["devise.#{provider}_data"] = request.env["omniauth.auth"]
				flash[:error] = "There was a problem signing you in through #{provider}."
				redirect_to new_user_registration_url
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login_helper
		if logged_in?(:editor, :admin)
		 (link_to "Logout", destroy_user_session_path, method: :delete)
		else
			(link_to "Register", new_user_registration_path) + " | " +
			(link_to "Login", new_user_session_path)
		end
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
		HTML

		html.html_safe
	end

	def devise_error_messages?
		!resource.errors.empty?
	end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>

  <% if blog.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <p><strong><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</strong></p>
      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :blog_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.user.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <% if logged_in?(:editor, :admin) %>
          <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
          <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path if logged_in?(:editor, :admin) %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user.name %>
</p>

<% if logged_in?(:editor, :admin) %>
	<%= link_to 'Edit', edit_blog_path(@blog) %> |
<% end %>
<%= link_to 'Back', blogs_path %>

app/views/layouts/_authentication.html.erb
<div class="row authentication">
	<div class="col-sm-4 offset-sm-8">
		<!--check that the current user is a User and not an OpenStruct obj(i.e. guest user)-->
		<%= login_helper %>
	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>">
		<a href="#" data-dismiss="alert" class="close">×</a>
		<ul>
			<li>
				<%= value %>
			</li>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseGoogleOmniauthDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>

    <div class="container">

      <%= render partial: 'layouts/authentication' %>
      <%= render partial: 'layouts/messages' %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome <%= current_user.first_name %></h1>